name: flutter_twind
description: Flutter UI components with Tailwind CSS-like styling system.
version: 0.1.4
homepage: https://github.com/QTTQ/flutter_twind
repository: https://github.com/QTTQ/flutter_twind
issue_tracker: https://github.com/QTTQ/flutter_twind/issues
documentation: https://github.com/QTTQ/flutter_twind#readme

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# 发布到 pub.dev 时的主题标签
topics:
  - ui
  - components
  - tailwind
  - design-system
  - theme

# 支持的平台
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
flutter:
